$(document).ready(function(){
	$(".content").slideUp();
	$("#personalTitle").click(function(){
		$("#personalTitle>.content").stop().slideToggle("slow");
	});
	$("#professionalTitle").click(function(){
		$("#professionalTitle>.content").stop().slideToggle("slow");
	});
	$("#hobbyTitle").click(function(){
		$("#hobbyTitle>.content").stop().slideToggle("slow");
	});
	$("#contactTitle").click(function(){
		$("#contactTitle>.content").stop().slideToggle("slow");
	});
});