$(document).ready(function(){
    var videoSoja=document.getElementById("soja");
    var videoManeva=document.getElementById("maneva");
	$("#border").hide();
	$("#divinit").hide();
    $("video").fadeOut();
    $(".content").hide();
    $(".content").slideUp();
    $("#pauseSoja").hide();
    $("#pauseManeva").hide();
    $("#showBorder").hide();
    $("#showDivinity").hide();
    $("#personal").click(function(){
        $("#personalTitle>.content").stop().slideToggle("slow");
    });
    $("#professional").click(function(){
        $("#professionalTitle>.content").stop().slideToggle("slow");
    });
    $("#hobby").click(function(){
        $("#hobbyTitle>.content").stop().slideToggle("slow");
    });
    $("#contact").click(function(){
        $("#contactTitle>.content").stop().slideToggle("slow");
    });
    $("#playSoja").click(function(){
        videoSoja.play();
        $("#playSoja").hide();
        $("#pauseSoja").show();
    });
    $("#pauseSoja").click(function(){
        videoSoja.pause();
        $("#pauseSoja").hide();
        $("#playSoja").show();
    });
    $("#replaySoja").click(function(){
        videoSoja.load();
        $("#pauseSoja").hide();
        $("#playSoja").show();
		$(this).rotate({angle:0,animateTo:180});
    });
    $("#playManeva").click(function(){
        videoManeva.play();
        $("#playManeva").hide();
        $("#pauseManeva").show();
    });
    $("#pauseManeva").click(function(){
        videoManeva.pause();
        $("#pauseManeva").hide();
        $("#playManeva").show();
    });
    $("#replayManeva").click(function(){
        videoManeva.load();
        $("#pauseManeva").hide();
        $("#playManeva").show();
		$(this).rotate({angle:0,animateTo:180});
    });	
    $("#hideBorder").click(function(){
        $("#border").fadeIn();
        $("#hideBorder").hide();
        $("#showBorder").show();
    });
    $("#showBorder").click(function(){
        $("#border").fadeOut();
        $("#hideBorder").show();
        $("#showBorder").hide();
    });
    $("#hideDivinity").click(function(){
        $("#divinit").fadeIn();
        $("#hideDivinity").hide();
        $("#showDivinity").show();
    });
    $("#showDivinity").click(function(){
        $("#divinit").fadeOut();
        $("#hideDivinity").show();
        $("#showDivinity").hide();
    });
});